---
dependency:
  name: galaxy
driver:
  name: delegated
  name_format: git
  auto_folder_path: /auto
lint: |
  set -e
  ansible-lint
platforms:
  - name: ARJAVA22
    template: Windows2022-GUI
provisioner:
  name: ansible
  log: true
  options:
    vvv: True
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer,junit
  playbooks:
    create: /drivers/vcenter/create.yml
    destroy: /drivers/vcenter/destroy.yml